# Generated by Django 3.1.1 on 2020-09-02 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
