# Generated by Django 3.1.1 on 2020-09-02 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_scraper', '0002_auto_20200902_2021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='description',
            new_name='content',
        ),
    ]
