# Generated by Django 3.1.1 on 2020-09-02 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news_scraper', '0003_auto_20200902_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('query', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='news_scraper.company'),
            preserve_default=False,
        ),
    ]
