# Generated by Django 3.1.1 on 2020-09-03 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_scraper', '0005_auto_20200902_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='hyperlinks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='images',
            field=models.TextField(blank=True, null=True),
        ),
    ]
