# Generated by Django 3.1.1 on 2020-09-03 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_scraper', '0006_auto_20200903_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('incomplete', 'Incomplete'), ('Completed', 'completed'), ('failed', 'Failed')], default='incomplete', max_length=10),
        ),
    ]
