# Generated by Django 3.1.1 on 2020-09-03 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_scraper', '0007_article_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('incomplete', 'Incomplete'), ('completed', 'Completed'), ('failed', 'Failed')], default='incomplete', max_length=10),
        ),
    ]
