# Generated by Django 3.1.1 on 2020-09-03 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_scraper', '0008_auto_20200903_0756'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.AddField(
            model_name='company',
            name='sources',
            field=models.ManyToManyField(to='news_scraper.Source'),
        ),
    ]
